/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trojx_ndkjnitest_NDKUtils */

#ifndef _Included_com_trojx_ndkjnitest_NDKUtils
#define _Included_com_trojx_ndkjnitest_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_trojx_ndkjnitest_NDKUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_trojx_ndkjnitest_NDKUtils_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
